Repository thoth-station/report-processing, pull requests merged in 2020-07, with the labels that each got.

#12 Added json to report from Qeb-hwt
  thoth/report_processing/adviser.py
Labels: approved, size/L

#14 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/L

#16 Release of version 0.1.0
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#11 Update security reports processing
  Pipfile
  Pipfile.lock
  requirements.txt
  tests/data/results/security-aggregated.json
  tests/data/security-indicators/security-indicators-54c6daf9/aggregated
  tests/data/security-indicators/security-indicators-54c6daf9/bandit
  tests/data/security-indicators/security-indicators-54c6daf9/cloc
  tests/data/security/aggregated.json
  tests/data/security/si_bandit/si-bandit-0a0050d5.json
  tests/data/security/si_cloc/si-cloc-0a0106ff.json
  tests/si_aggregator_test.py
  tests/si_bandit_test.py
  tests/si_cloc_test.py
  thoth/report_processing/components/security.py
  thoth/report_processing/enums.py
  thoth/report_processing/utils.py
Labels: approved, size/XXL

#17 Add new adviser methods to Adviser class
  Pipfile
  Pipfile.lock
  tests/adviser_test.py
  tests/data/adviser/adviser-22a89155.json
  tests/data/adviser/adviser-e82b5ff8.json
  thoth/report_processing/adviser.py
  thoth/report_processing/components/__init__.py
  thoth/report_processing/components/adviser.py
  thoth/report_processing/components/security.py
Labels: approved, size/XXL

#19 Release of version 0.2.0
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#20 Adjust methods
  tests/adviser_test.py
  thoth/report_processing/components/adviser.py
  thoth/report_processing/components/security.py
Labels: approved, size/M

#22 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/L

#23 Release of version 0.2.1
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#26 Add missing packages to requirements.txt
  requirements.txt
Labels: approved, size/XS

#28 Release of version 0.2.2
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#29 python script name changed and therefore metadata
  thoth/report_processing/components/security.py
Labels: approved, size/XS

#30 Automatic update of dependency pandas from 1.0.5 to 1.1.0
  Pipfile.lock
Labels: approved, bot, size/L
