Repository thoth-station/report-processing, pull requests merged in 2020-09, with the labels that each got.

#51 Merge statistics and results
  Pipfile
  Pipfile.lock
  thoth/report_processing/components/inspection.py
Labels: size/XL

#56 Release of version 0.3.1
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/S

#57 Update requirements
  requirements.txt
Labels: approved, size/XS

#59 Release of version 0.3.2
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#60 Use singular for consistency
  tests/data/security-indicator/security-indicator-54c6daf9/aggregated
  tests/data/security-indicator/security-indicator-54c6daf9/bandit
  tests/data/security-indicator/security-indicator-54c6daf9/cloc
  tests/si_aggregator_test.py
  tests/si_bandit_test.py
  tests/si_cloc_test.py
  thoth/report_processing/components/security.py
Labels: approved, size/M

#63 Release of version 0.3.3
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/S

#64 Output df for comparison of results and make performance parameters optional
  thoth/report_processing/components/inspection.py
Labels: approved, size/M

#66 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/L

#67 Automatic update of dependency pandas from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#68 Automatic update of dependency pandas from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: approved, bot, size/M
