Repository thoth-station/report-processing, pull requests merged in 2020-10, with the labels that each got.

#70 Select adviser-version
  tests/adviser_test.py
  tests/data/results/security-aggregated.json
  tests/data/security-indicator/security-indicator-rererrer/aggregated
  tests/data/security-indicator/security-indicator-rererrer/bandit
  tests/data/security-indicator/security-indicator-rererrer/cloc
  tests/data/security-indicator/security-indicator-terterer/aggregated
  tests/data/security-indicator/security-indicator-terterer/bandit
  tests/data/security-indicator/security-indicator-terterer/cloc
  tests/si_aggregator_test.py
  tests/si_bandit_test.py
  thoth/report_processing/components/adviser.py
  thoth/report_processing/components/security.py
Labels: approved, size/L

#72 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/L

#74 Automatic update of dependency pandas from 1.1.2 to 1.1.3
  Pipfile.lock
Labels: approved, bot, size/L

#76 Automatic update of dependency numpy from 1.19.1 to 1.19.2
  Pipfile.lock
Labels: approved, bot, size/L

#79 Automatic update of dependency pytest from 6.0.1 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/L

#80 Release of version 0.3.5
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/S
