Repository thoth-station/report-processing, pull requests merged in 2020-08, with the labels that each got.

#31 Add Inspection class
  Pipfile.lock
  tests/adviser_test.py
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/0/hwinfo
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/0/log
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/0/result
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/1/hwinfo
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/1/log
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/results/1/result
  tests/inspection_test.py
  tests/si_aggregator_test.py
  tests/si_bandit_test.py
  thoth/report_processing/components/__init__.py
  thoth/report_processing/components/adviser.py
  thoth/report_processing/components/inspection.py
  thoth/report_processing/components/security.py
  thoth/report_processing/enums.py
Labels: approved, size/XXL

#33 Release of version 0.2.3
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#34 Adjust range for daily analysis
  thoth/report_processing/components/adviser.py
Labels: approved, size/XS

#36 Release of version 0.2.4
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#38 Feature: add AmunInspectionStatistics class
  tests/inspection_test.py
  thoth/report_processing/components/__init__.py
  thoth/report_processing/components/inspection.py
Labels: approved, size/L

#37 Add solver class
  tests/data/solver/solver-fedora-31-py37-012b745d
  tests/solver_test.py
  thoth/report_processing/components/__init__.py
  thoth/report_processing/components/solver.py
Labels: approved, size/XXL

#40 Release of version 0.3.0
  CHANGELOG.md
  thoth/report_processing/__init__.py
Labels: approved, bot, size/XS

#42 Default to Ceph
  README.rst
  tests/si_cloc_test.py
  thoth/report_processing/components/security.py
Labels: approved, size/S

#41 Add parameter to performance results
  thoth/report_processing/components/inspection.py
Labels: approved, size/XS

#43 Add filters for runtime environment
  tests/inspection_test.py
  thoth/report_processing/components/inspection.py
Labels: approved, size/L

#44 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/L

#45 Automatic update of dependency pandas from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/M

#46 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#48 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/L

#47 Automatic update of dependency pylint from 2.5.3 to 2.6.0
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#50 Automatic update of dependency pylint from 2.5.3 to 2.6.0
  Pipfile.lock
Labels: approved, bot, size/S
