Repository thoth-station/report-processing, pull requests merged in 2021-11, with the labels that each got.

#140 Fix missing tab in inspection.py
  thoth/report_processing/components/inspection.py
Labels: approved, size/S

#143 Adding my username to the list of maintainers
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#149 Fix test execution in prow
  setup.py
Labels: approved, size/M

#146 Fix relative import of `base_test` in test files
  MANIFEST.in
  tests/adviser_test.py
  tests/inspection_test.py
  tests/si_aggregator_test.py
  tests/solver_test.py
Labels: size/M

#151 Fix tests and update data
  .gitignore
  .prow.yaml
  mypy.ini
  setup.py
  tests/adviser_test.py
  tests/data/adviser/adviser-211123195453-bb9f6846b33a9810.json
  tests/data/adviser/adviser-ffd8c522
  tests/data/inspections/inspection-iotf-2-matmul-u38m-fd697eb4/build/Dockerfile
  tests/data/inspections/inspection-iotf-2-matmul-u38m-fd697eb4/build/log
  tests/data/inspections/inspection-iotf-2-matmul-u38m-fd697eb4/build/specification
  tests/data/inspections/inspection-rhtf-conv2d-21090f6e/build/log
  tests/data/inspections/inspection-rhtf-conv2d-21090f6e/build/specification
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/build/log
  tests/data/inspections/inspection-tfcpu-matmul-5e5a1563/build/specification
  tests/data/results/security-aggregated.json
  tests/data/security-indicator/security-indicator-rererrer/aggregated
  tests/data/security-indicator/security-indicator-rererrer/bandit
  tests/data/security-indicator/security-indicator-terterer/aggregated
  tests/data/security-indicator/security-indicator-terterer/bandit
  tests/data/security-indicator/security-indicator-terterer/cloc
  tests/data/security-indicators/security-indicator-211124154025-de8d82a3227adc99/bandit
  tests/data/security-indicators/security-indicator-211124154025-de8d82a3227adc99/cloc
  tests/inspection_test.py
  tests/si_aggregator_test.py
  tests/si_bandit_test.py
  tests/si_cloc_test.py
  thoth/report_processing/components/adviser.py
  thoth/report_processing/components/inspection.py
  thoth/report_processing/components/security.py
Labels: approved, size/XXL

#154 Add github template for missing module
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/S
