Repository thoth-station/report-processing, pull requests merged in 2022-03, with the labels that each got.

#159 Fix key error for create_inspections_dataframe
  thoth/report_processing/components/inspection.py
Labels: size/XS

#164 Fix tests and creating python package Dataframes
  tests/data/results/security-aggregated.json
  tests/si_bandit_test.py
  thoth/report_processing/components/inspection.py
Labels: approved, size/M

#156 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: approved, size/XS, lifecycle/stale
